name: Pokedex website healthcheck
on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  health-check-request:
    runs-on: ubuntu-20.04
    steps:
      - name: Run healthcheck on the website
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://silent-hill-9183.fly.dev/
          max-attempts: 3 # Optional, defaults to 1
          retry-all: false # Optional, defaults to "false"

